// src/admin/utils/csvExport.js
// Utility functions for CSV export with document-style headers

/**
 * Export data to a CSV file with a branded document header.
 * @param {Array}  data     - Array of flat objects (one per row)
 * @param {string} filename - Base filename (without extension or date)
 * @param {Object} meta     - Optional metadata for the header block
 *   meta.title       - Report title (defaults to prettified filename)
 *   meta.adminName   - Name of the admin who exported
 *   meta.department  - Admin department/role label
 *   meta.dateRange   - Human-readable period string, e.g. "Jan 1 – Jun 15, 2026"
 */
export function exportToCSV(data, filename, meta = {}) {
  if (!data || data.length === 0) {
    alert('No data to export');
    return;
  }

  const headers = Object.keys(data[0]);

  const dateStr = new Date().toLocaleString('en-PH', {
    year: 'numeric', month: 'long', day: 'numeric',
    hour: '2-digit', minute: '2-digit'
  });

  const prettyTitle = meta.title ||
    filename
      .replace(/_/g, ' ')
      .replace(/-/g, ' ')
      .replace(/\b\w/g, c => c.toUpperCase());

  const byLine = [
    meta.adminName,
    meta.department ? `(${meta.department})` : null
  ].filter(Boolean).join(' ') || 'Admin';

  // Document header rows — each cell wrapped in quotes so commas are safe
  const docRows = [
    'NUCash University Cashless Payment System',
    `Report: ${prettyTitle}`,
    `Generated by: ${byLine}`,
    `Date: ${dateStr}`,
    ...(meta.dateRange ? [`Period: ${meta.dateRange}`] : []),
    '',  // blank separator before data
  ].map(line => `"${String(line).replace(/"/g, '""')}"`);

  // Data rows
  const dataRows = data.map(row =>
    headers.map(key => {
      const value = row[key];
      if (value === null || value === undefined) return '';
      const s = String(value);
      return s.includes(',') || s.includes('"') || s.includes('\n')
        ? `"${s.replace(/"/g, '""')}"`
        : s;
    }).join(',')
  );

  const csvContent = [
    ...docRows,
    headers.join(','),
    ...dataRows,
  ].join('\n');

  // UTF-8 BOM so Excel opens it correctly without garbling PH names / ₱ signs
  const BOM = '﻿';
  const blob = new Blob([BOM + csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename}_${new Date().toISOString().split('T')[0]}.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);

  // Tell the app the export finished — the global ExportCompleteModal
  // (mounted in App) shows the success dialog on every page for free.
  window.dispatchEvent(new CustomEvent('nucash:export-complete', {
    detail: {
      message: `${prettyTitle} exported to CSV successfully (${data.length} record${data.length !== 1 ? 's' : ''}).`
    }
  }));
}

/**
 * Strip internal fields and format dates from raw API objects before export.
 */
export function prepareDataForExport(data, fieldsToExclude = ['_id', '__v', 'password', 'pin']) {
  return data.map(item => {
    const cleaned = {};
    Object.keys(item).forEach(key => {
      if (!fieldsToExclude.includes(key)) {
        const val = item[key];
        if (val instanceof Date || (typeof val === 'string' && /^\d{4}-\d{2}-\d{2}T/.test(val))) {
          cleaned[key] = new Date(val).toLocaleString('en-PH');
        } else if (val && typeof val === 'object' && !Array.isArray(val)) {
          // Flatten one level of nested objects (e.g. populated refs)
          cleaned[key] = JSON.stringify(val);
        } else {
          cleaned[key] = val;
        }
      }
    });
    return cleaned;
  });
}
