// nucash-server/utils/csvExporter.js
// Single source of truth for ALL CSV exports — tab "Export CSV" buttons,
// Settings manual/scheduled exports, and the auto-export cron all funnel
// through exportByType() here, so every export of a given type has identical
// columns, identical contents, and the same branded document header
// regardless of where it was triggered or by which admin.

import Driver from '../models/Driver.js';
import Shuttle from '../models/Shuttle.js';
import Route from '../models/Route.js';
import Phone from '../models/Phone.js';
import Trip from '../models/Trip.js';
import Transaction from '../models/Transaction.js';
import EventLog from '../models/EventLog.js';
import User from '../models/User.js';
import UserConcern from '../models/UserConcern.js';
import Merchant from '../models/Merchant.js';
import Admin from '../models/Admin.js';
import { buildDepartmentLogQuery, buildDepartmentConcernQuery, buildDepartmentPhoneQuery } from './exportScopes.js';

// ---------------------------------------------------------------------------
// Shared CSV builder — mirrors client/src/utils/csvExport.js exactly so a
// download from a tab and a download from Settings are byte-for-byte the same.
// ---------------------------------------------------------------------------

const esc = (v) => {
  if (v === null || v === undefined) return '';
  const s = String(v);
  return s.includes(',') || s.includes('"') || s.includes('\n')
    ? `"${s.replace(/"/g, '""')}"`
    : s;
};

const fmtDateTime = (d) => d ? new Date(d).toLocaleString('en-PH', {
  year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit'
}) : '';
const fmtDate = (d) => d ? new Date(d).toLocaleDateString('en-PH', { year: 'numeric', month: 'short', day: 'numeric' }) : '';
const fmtTime = (d) => d ? new Date(d).toLocaleTimeString('en-PH', { hour: '2-digit', minute: '2-digit' }) : '';
const yesNo = (b) => (b ? 'Yes' : 'No');

/**
 * Wrap column headers + row objects in the branded NUCash document header.
 * @param {string} title    report title, e.g. "Routes Report"
 * @param {string[]} headers ordered column labels (also the keys into each row)
 * @param {object[]} rows    row objects keyed by the header labels
 * @param {object} meta      { adminName, department, dateRange }
 * @returns {string} full CSV text with a UTF-8 BOM
 */
function buildBrandedCsv(title, headers, rows, meta = {}) {
  const dateStr = new Date().toLocaleString('en-PH', {
    year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit'
  });
  const byLine = [meta.adminName, meta.department ? `(${meta.department})` : null]
    .filter(Boolean).join(' ') || 'Admin';

  const docRows = [
    'NUCash University Cashless Payment System',
    `Report: ${title}`,
    `Generated by: ${byLine}`,
    `Date: ${dateStr}`,
    ...(meta.dateRange ? [`Period: ${meta.dateRange}`] : []),
    '',
  ].map((line) => `"${String(line).replace(/"/g, '""')}"`);

  const headerRow = headers.map(esc).join(',');
  const dataRows = rows.map((row) => headers.map((h) => esc(row[h])).join(','));

  const BOM = '﻿';
  return BOM + [...docRows, headerRow, ...dataRows].join('\n');
}

// Apply a createdAt (or custom field) date window to a query, if provided.
const withDateFilter = (query, dateFilter, field = 'createdAt') => {
  if (dateFilter?.startDate && dateFilter?.endDate) {
    query[field] = { $gte: new Date(dateFilter.startDate), $lte: new Date(dateFilter.endDate) };
  }
  return query;
};

const driverName = (d) => `${d.firstName || ''}${d.middleInitial ? ' ' + d.middleInitial + '.' : ''} ${d.lastName || ''}`.replace(/\s+/g, ' ').trim();

// ---------------------------------------------------------------------------
// Per-type definitions: { title, headers, rows }
// Each returns friendly, correctly-mapped columns pulled from real model fields.
// ---------------------------------------------------------------------------

export async function exportDrivers(dateFilter = {}) {
  const drivers = await Driver.find(withDateFilter({}, dateFilter)).sort({ driverId: 1 }).lean();
  const headers = ['Driver ID', 'Name', 'Email', 'Assigned Shuttle', 'License Number', 'License Expiry', 'Active', 'Created'];
  const rows = drivers.map((d) => ({
    'Driver ID': d.driverId,
    'Name': driverName(d),
    'Email': d.email,
    'Assigned Shuttle': d.shuttleId || '',
    'License Number': d.licenseNumber || '',
    'License Expiry': fmtDate(d.licenseExpiry),
    'Active': yesNo(d.isActive),
    'Created': fmtDate(d.createdAt),
  }));
  return { title: 'Drivers Report', headers, rows };
}

export async function exportShuttles(dateFilter = {}) {
  const shuttles = await Shuttle.find(withDateFilter({}, dateFilter)).sort({ shuttleId: 1 }).lean();
  const headers = ['Shuttle ID', 'Vehicle Type', 'Model', 'Plate Number', 'Capacity', 'Status', 'Active', 'Created'];
  const rows = shuttles.map((s) => ({
    'Shuttle ID': s.shuttleId,
    'Vehicle Type': s.vehicleType || '',
    'Model': s.vehicleModel || '',
    'Plate Number': s.plateNumber || '',
    'Capacity': s.capacity ?? '',
    'Status': s.status || '',
    'Active': yesNo(s.isActive),
    'Created': fmtDate(s.createdAt),
  }));
  return { title: 'Shuttles Report', headers, rows };
}

export async function exportRoutes(dateFilter = {}) {
  const routes = await Route.find(withDateFilter({}, dateFilter)).sort({ order: 1, routeId: 1 }).lean();
  const headers = ['Route ID', 'Route Name', 'From', 'To', 'Fare', 'Active', 'Order', 'Created'];
  const rows = routes.map((r) => ({
    'Route ID': r.routeId,
    'Route Name': r.routeName,
    'From': r.fromName || '',
    'To': r.toName || '',
    'Fare': r.fare ?? 0,
    'Active': yesNo(r.isActive),
    'Order': r.order ?? '',
    'Created': fmtDate(r.createdAt),
  }));
  return { title: 'Routes Report', headers, rows };
}

export async function exportPhones(dateFilter = {}, role = null) {
  const query = withDateFilter(buildDepartmentPhoneQuery(role), dateFilter);
  const phones = await Phone.find(query).sort({ phoneId: 1 }).lean();
  const headers = ['Phone ID', 'Model', 'Type', 'Assigned To', 'Assignment ID', 'Status', 'Notes', 'Created'];
  const rows = phones.map((p) => ({
    'Phone ID': p.phoneId,
    'Model': p.phoneModel || '',
    'Type': p.phoneType || '',
    'Assigned To': p.assignedDriverName || p.assignedBusinessName || '',
    'Assignment ID': p.assignedDriverId || p.assignedMerchantId || '',
    'Status': p.status || '',
    'Notes': p.notes || '',
    'Created': fmtDate(p.createdAt),
  }));
  return { title: 'Devices Report', headers, rows };
}

export async function exportTrips(dateFilter = {}) {
  const trips = await Trip.find(withDateFilter({}, dateFilter)).sort({ departureTime: -1 }).lean();
  const headers = ['Trip ID', 'Shuttle ID', 'Driver', 'Route ID', 'Departure', 'Arrival', 'Duration (min)', 'Passengers', 'Collections', 'Status', 'Created'];
  const rows = trips.map((t) => ({
    'Trip ID': t.tripId,
    'Shuttle ID': t.shuttleId || '',
    'Driver': t.driverName || t.driverId || '',
    'Route ID': t.routeId || '',
    'Departure': fmtDateTime(t.departureTime),
    'Arrival': fmtDateTime(t.arrivalTime),
    'Duration (min)': t.durationMinutes ?? '',
    'Passengers': t.passengerCount || 0,
    'Collections': t.totalCollections || 0,
    'Status': t.status || '',
    'Created': fmtDate(t.createdAt),
  }));
  return { title: 'Trips Report', headers, rows };
}

// Build a userId -> "Full Name" map for transaction-style exports (Transaction
// docs store schoolUId/email but not the member's name).
async function nameMapForTransactions(txs) {
  const ids = [...new Set(txs.map((t) => t.userId).filter(Boolean).map(String))];
  if (ids.length === 0) return {};
  const users = await User.find({ _id: { $in: ids } }).select('firstName lastName').lean();
  return Object.fromEntries(users.map((u) => [String(u._id), `${u.firstName || ''} ${u.lastName || ''}`.trim()]));
}

export async function exportTransactions(dateFilter = {}) {
  const txs = await Transaction.find(withDateFilter({}, dateFilter)).sort({ createdAt: -1 }).lean();
  const names = await nameMapForTransactions(txs);
  const headers = ['Date', 'Time', 'ID Number', 'Name', 'Email', 'Type', 'Status', 'Amount', 'Balance After', 'Transaction ID'];
  const rows = txs.map((t) => ({
    'Date': fmtDate(t.createdAt),
    'Time': fmtTime(t.createdAt),
    'ID Number': t.schoolUId || '',
    'Name': names[String(t.userId)] || '',
    'Email': t.email || '',
    'Type': t.transactionType === 'credit' ? 'Cash-In' : 'Payment',
    'Status': t.status || '',
    'Amount': t.amount ?? 0,
    'Balance After': t.balance ?? '',
    'Transaction ID': t.transactionId || '',
  }));
  return { title: 'Transactions Report', headers, rows };
}

export async function exportCashIns(dateFilter = {}) {
  // Cash-ins are credits, excluding student-to-student transfers.
  const query = withDateFilter({ transactionType: 'credit', transferPeerSchoolId: null }, dateFilter);
  const txs = await Transaction.find(query).sort({ createdAt: -1 }).lean();
  const names = await nameMapForTransactions(txs);
  const headers = ['Date', 'Time', 'ID Number', 'Name', 'Email', 'Amount', 'Status', 'Transaction ID'];
  const rows = txs.map((t) => ({
    'Date': fmtDate(t.createdAt),
    'Time': fmtTime(t.createdAt),
    'ID Number': t.schoolUId || '',
    'Name': names[String(t.userId)] || '',
    'Email': t.email || '',
    'Amount': t.amount ?? 0,
    'Status': t.status || '',
    'Transaction ID': t.transactionId || '',
  }));
  return { title: 'Cash-Ins Report', headers, rows };
}

export async function exportLogs(dateFilter = {}, role = null) {
  const query = withDateFilter(buildDepartmentLogQuery(role), dateFilter, 'timestamp');
  const logs = await EventLog.find(query).sort({ timestamp: -1 }).lean();
  const headers = ['Date', 'Time', 'Event', 'Description', 'Department', 'Admin', 'Admin ID', 'Target', 'Severity', 'IP Address'];
  const rows = logs.map((l) => ({
    'Date': fmtDate(l.timestamp || l.createdAt),
    'Time': fmtTime(l.timestamp || l.createdAt),
    'Event': l.title || l.eventType || '',
    'Description': l.description || '',
    'Department': l.department || '',
    'Admin': l.adminName || '',
    'Admin ID': l.adminId || '',
    'Target': l.targetEntity || '',
    'Severity': l.severity || '',
    'IP Address': l.ipAddress || '',
  }));
  return { title: 'Activity Logs Report', headers, rows };
}

export async function exportUsers(dateFilter = {}) {
  const users = await User.find(withDateFilter({}, dateFilter)).sort({ createdAt: -1 }).lean();
  const headers = ['ID Number', 'RFID', 'Name', 'Email', 'Role', 'Status', 'Deactivated', 'Balance', 'Created'];
  const rows = users.map((u) => ({
    'ID Number': u.schoolUId || '',
    'RFID': u.rfidUId || '',
    'Name': `${u.firstName || ''} ${u.lastName || ''}`.trim(),
    'Email': u.email || '',
    'Role': u.role || '',
    'Status': u.isActive ? 'Active' : 'Inactive',
    'Deactivated': yesNo(u.isDeactivated),
    'Balance': u.balance || 0,
    'Created': fmtDate(u.createdAt),
  }));
  return { title: 'User Management Report', headers, rows };
}

export async function exportConcerns(dateFilter = {}, role = null) {
  const query = withDateFilter(buildDepartmentConcernQuery(role), dateFilter, 'submittedAt');
  const concerns = await UserConcern.find(query).sort({ submittedAt: -1 }).lean();
  const headers = ['Concern ID', 'Type', 'Name', 'Email', 'Subject', 'Concerns', 'Feedback', 'Rating', 'Report To', 'Priority', 'Status', 'Submitted'];
  const rows = concerns.map((c) => ({
    'Concern ID': c.concernId,
    'Type': c.submissionType || '',
    'Name': c.userName || '',
    'Email': c.userEmail || '',
    'Subject': c.subject || '',
    'Concerns': (c.selectedConcerns || []).join('; '),
    'Feedback': c.feedbackText || '',
    'Rating': c.rating ?? '',
    'Report To': c.reportTo || '',
    'Priority': c.priority || '',
    'Status': c.status || '',
    'Submitted': fmtDateTime(c.submittedAt),
  }));
  return { title: 'Concerns Report', headers, rows };
}

export async function exportMerchants(dateFilter = {}) {
  const merchants = await Merchant.find(withDateFilter({}, dateFilter)).select('-pin -password').sort({ merchantId: 1 }).lean();
  const headers = ['Merchant ID', 'Business Name', 'Contact Person', 'Email', 'License Number', 'License Expiry', 'Active', 'Created'];
  const rows = merchants.map((m) => ({
    'Merchant ID': m.merchantId || '',
    'Business Name': m.businessName || '',
    'Contact Person': `${m.firstName || ''} ${m.lastName || ''}`.trim(),
    'Email': m.email || '',
    'License Number': m.licenseNumber || '',
    'License Expiry': fmtDate(m.licenseExpiry),
    'Active': yesNo(m.isActive),
    'Created': fmtDate(m.createdAt),
  }));
  return { title: 'Merchants Report', headers, rows };
}

export async function exportBalances(dateFilter = {}) {
  const users = await User.find(withDateFilter({}, dateFilter)).sort({ balance: -1 }).lean();
  const headers = ['ID Number', 'Name', 'Email', 'Role', 'Balance', 'Active', 'Created'];
  const rows = users.map((u) => ({
    'ID Number': u.schoolUId || '',
    'Name': `${u.firstName || ''} ${u.lastName || ''}`.trim(),
    'Email': u.email || '',
    'Role': u.role || '',
    'Balance': u.balance || 0,
    'Active': yesNo(u.isActive),
    'Created': fmtDate(u.createdAt),
  }));
  return { title: 'User Balances Report', headers, rows };
}

export async function exportAdmins(dateFilter = {}) {
  const admins = await Admin.find(withDateFilter({}, dateFilter)).select('-pin -password').sort({ adminId: 1 }).lean();
  const headers = ['Admin ID', 'ID Number', 'Name', 'Email', 'Role', 'Active', 'Created'];
  const rows = admins.map((a) => ({
    'Admin ID': a.adminId ?? '',
    'ID Number': a.schoolUId || '',
    'Name': `${a.firstName || ''} ${a.lastName || ''}`.trim(),
    'Email': a.email || '',
    'Role': a.role || '',
    'Active': yesNo(a.isActive),
    'Created': fmtDate(a.createdAt),
  }));
  return { title: 'Administrators Report', headers, rows };
}

export async function exportCampaigns(dateFilter = {}) {
  const PromotionCampaign = (await import('../models/PromotionCampaign.js')).default;
  const campaigns = await PromotionCampaign.find(withDateFilter({}, dateFilter)).sort({ createdAt: -1 }).lean();
  const rewardLabel = (c) => {
    const v = c.rewardValue ?? 1;
    if (c.rewardType === 'discount') return `${v}% Off`;
    if (c.rewardType === 'credit') return `₱${v} Credit`;
    return v > 1 ? `${v} Free Rides` : 'Free Ride';
  };
  const headers = ['Title', 'Description', 'Reward Type', 'Reward', 'Minimum Rides', 'Frequency', 'Active', 'Rewards Sent', 'Last Run', 'Created'];
  const rows = campaigns.map((c) => ({
    'Title': c.title,
    'Description': c.description || '',
    'Reward Type': c.rewardType || '',
    'Reward': rewardLabel(c),
    'Minimum Rides': c.minimumRides ?? '',
    'Frequency': c.frequency || '',
    'Active': yesNo(c.active),
    'Rewards Sent': c.rewardsSent || 0,
    'Last Run': fmtDate(c.lastRunDate),
    'Created': fmtDate(c.createdAt),
  }));
  return { title: 'Promotional Campaigns Report', headers, rows };
}

// ---------------------------------------------------------------------------
// Dispatcher — the ONE entry point used everywhere.
// Returns { csv, count } where csv already carries the branded document header.
// ---------------------------------------------------------------------------
export async function exportByType(exportType, dateFilter = {}, role = null, meta = {}) {
  const normalizedType = String(exportType).toLowerCase().replace(/\s+/g, '-');

  let result;
  switch (normalizedType) {
    case 'drivers': result = await exportDrivers(dateFilter); break;
    case 'shuttles': result = await exportShuttles(dateFilter); break;
    case 'routes': result = await exportRoutes(dateFilter); break;
    case 'phones': result = await exportPhones(dateFilter, role); break;
    case 'trips': result = await exportTrips(dateFilter); break;
    case 'transactions': result = await exportTransactions(dateFilter); break;
    case 'logs': result = await exportLogs(dateFilter, role); break;
    case 'users': result = await exportUsers(dateFilter); break;
    case 'concerns': result = await exportConcerns(dateFilter, role); break;
    case 'merchants': result = await exportMerchants(dateFilter); break;
    case 'cash-ins':
    case 'cashins': result = await exportCashIns(dateFilter); break;
    case 'balances': result = await exportBalances(dateFilter); break;
    case 'admins': result = await exportAdmins(dateFilter); break;
    case 'campaigns': result = await exportCampaigns(dateFilter); break;
    default: throw new Error(`Unknown export type: ${exportType}`);
  }

  const csv = buildBrandedCsv(result.title, result.headers, result.rows, meta);
  return { csv, count: result.rows.length, title: result.title };
}

// Friendly department label for the branded "Generated by" line.
export const roleDepartmentLabel = (role) => {
  const map = { sysad: 'System Administrator', treasury: 'Treasury', accounting: 'Accounting', marketing: 'Marketing', motorpool: 'Motorpool', merchant: 'Merchant Management' };
  return map[role] || (role ? role.charAt(0).toUpperCase() + role.slice(1) : '');
};
